author: yanm1ng # 作者
description: yanm1ng's blog
keyword: hexo-theme, vuejs
favicon: 

excerpt_link: Read more

menu:
 主页: /
 分类: /tags/
 归档: /archives/
# Projects: /project/
 大佬们: /links/
 关于: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: false

# qrcode
qrcode: false

# comment
# you can set gitment or uyan

comment: gitment

# gitment config
gitment_owner: haozi23333
gitment_repo: haozi23333.github.io
gitment_oauth_id: 20421b02a1526d225183
gitment_oauth_secret: 375652780feb5a3ae8c0b8326d52b96517f33c9f

# uyan
# if you want to use uyan as your blog comment, plz remove/comment out gitment config

baidu_id: 

about: 
  banner: https://file.muyutech.com/about.jpg
  avatar: https://avatars3.githubusercontent.com/u/16443628?v=3&s=460
  description: "The end is always near."
#  weibo_username: yanm1ng
#  twitter_username: yanm1ng
#  github_username: yanm1ng
#  zhihu_username: yummy1121
#  douban_username: yanm1ng

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
